### ISSUE TITLE
Drop the rotating buttons

### ISSUE THREAD

**Issue by algernon** [algernon/mastodon-material-tweaks#6]
Rotating the buttons wasn't a terribly good idea, drop it. Instead, use colors. The reason I didn't use colors before was due to the `fa-retweet` having a custom SVG background.

We can get rid of that with something like this:

```css
.fa-retweet::before {
  content: "";
}
.fa-retweet::after {
  content: "\f079";
}
.button.icon-button i.fa-retweet {
  background-image: none !important;
}
```
